### ISSUE TITLE
Prevents app login, fills logs with errors for already authed users

### ISSUE THREAD

**Issue by strayobject** [owncloud/twofactor_totp#42]
Installed on OC 10.0.4.4 this module does not seem to be compatible with android mobile app or 'aCalDav' adapter for android.
It prevents new users from being able to authenticate and for those who have connected their mobile app before enabling TOTP it generates a lot of `"message":"Login failed: <username> (Remote IP: <ip>)"` errors in the owncloud.log (does not impede the use of already authenticated mobile app though)
I do not own apple products, so cannot test iOS app.

**Comment by patrickjahns** [comment]
Can you please provide the following information:
- Exact steps to reproduce
- The relevant lines from `owncloud.log`

@karakayasemi 
could help to verify this?

**Comment by karakayasemi** [comment]
I do not think the problem is related to the application. If totp is enabled, the current mobile clients only support the use of application code. Also, a lot of login failed case is probably related to owncloud/core. @strayobject If you give more details and exact reproducing steps, I can try to debug.

**Comment by karakayasemi** [comment]
@strayobject your problems are probably related to https://github.com/owncloud/core/issues/30157. Please track 10.0.7 hotfix release, if your problems still exist feel free to open this issue again by specifying exact reproduce steps.
